services:
  typesense:
    image: typesense/typesense:27.1
    ports:
      - 8108:8108
    volumes:
      - typesense:/data
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}

volumes:
  typesense: