volumes:
  caddy_data:
  caddy_config:

services:
  caddy:
    image: caddy:2.8
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_SCHEME: ${DOMAIN_SCHEME:?DOMAIN_SCHEME is not set}
      DOMAIN_NAME: ${DOMAIN_NAME:?DOMAIN_NAME is not set}
    volumes:
      - ../:/etc/caddy/common
      - ../../Caddyfile/:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
     - host.docker.internal:host-gateway