services:
  dmp_cms_backend_cron:
      image: ghcr.io/${org}/dmp-cms-backend-crone:${DMP_CMS_Backend_CRON_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
      restart: always
      environment:
        GITHUB_TOKEN: ${GITHUB_TOKEN:?GITHUB_TOKEN is not set}
        TARGET_DATE: ${TARGET_DATE:?TARGET_DATE is not set}
        SUPABASE_URL: ${SUPABASE_URL:?SUPABASE_URL is not set}
        SUPABASE_KEY: ${SUPABASE_KEY:?SUPABASE_KEY is not set}
        SCHEDULER_DELAY_IN_MINS: ${SCHEDULER_DELAY_IN_MINS:?SCHEDULER_DELAY_IN_MINS is not set}
        POSTGRES_DB_HOST: ${POSTGRES_DB_HOST:?POSTGRES_DB_HOST is not set}
        POSTGRES_DB_NAME: ${POSTGRES_DB_NAME:?POSTGRES_DB_NAME is not set}
        POSTGRES_DB_USER: ${POSTGRES_DB_USER:?POSTGRES_DB_USER is not set}
        POSTGRES_DB_PASS: ${POSTGRES_DB_PASS:?POSTGRES_DB_PASS is not set}