services:
  pgweb:
    image: sosedoff/pgweb
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 5s
    mem_limit: ${PGWEB_MEM_LIMIT:-256m}
    environment:
      - PGWEB_DATABASE_URL=${PGWEB_DATABASE_URL}