services:
  pgweb:
    image: sosedoff/pgweb
    restart: always
    depends_on:
    - db
    environment:
    - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/pgweb?sslmode=disable