services:
  postgis:
    image: postgis/postgis:16-3.4-alpine
    restart: always
    volumes:
      - postgis:/var/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGIS_USER: ${POSTGIS_USER:?POSTGIS_USER is not set}
      POSTGIS_PASSWORD: ${POSTGIS_PASSWORD:?POSTGIS_PASSWORD is not set}

volumes:
  postgis:
