  services:
    hasura:
      image: hasura/graphql-engine:latest
      restart: always
      environment:
        HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
        HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET:?HASURA_GRAPHQL_ADMIN_SECRET is not set}
      healthcheck:
        test: ['CMD', 'curl', '-f', 'http://localhost:8080/healthz']
        interval: 10s
        timeout: 10s
        retries: 5