{
 "title": "GPU Metrics Dashboard",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.19+) cluster",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "GPU",
    "label": "GPU",
    "query": {
     "query": "label_values(DCGM_FI_DEV_ENC_UTIL,UUID)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(UUID) (DCGM_FI_DEV_GPU_TEMP{UUID=\"$GPU\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{UUID=\"$GPU\"})",
     "legendFormat": "{{namespace}} : {{container}}: {{DCGM_FI_DEV_GPU_TEMP}}"
    }
   ]
  },
  {
   "title": "Memory Metrics",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_FB_USED{UUID=\"$GPU\"})",
     "legendFormat": "USED"
    },
    {
     "expr": "avg(DCGM_FI_DEV_FB_FREE{UUID=\"$GPU\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{UUID=\"$GPU\"}",
     "legendFormat": "{{namespace}} : {{container}}: {{DCGM_FI_DEV_POWER_USAGE}}  "
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_POWER_USAGE{UUID=\"$GPU\"})",
     "legendFormat": "{{namespace}} : {{container}}: {{DCGM_FI_DEV_POWER_USAGE}}  "
    }
   ]
  }
 ]
}