{
 "title": "Kong (New)",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(kong_http_requests_total,service)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(kong_http_requests_total,route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Max RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(kong_http_requests_total{service=~\"$service\",route=~\"$route\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(rate(kong_http_requests_total{service=~\"$service\",route=~\"$route\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code=~\"1..\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1xx Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code=~\"1..\"}[$__interval])) / sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\"}[$__interval])) * 100",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "2xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code=~\"2..\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code=~\"2..\"}[$__interval])) / sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code=~\"3..\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3xx Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code=~\"3..\"}[$__interval])) / sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code=~\"4..\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code=~\"4..\"}[$__interval])) / sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code=~\"5..\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code=~\"5..\"}[$__interval])) / sum(sum_over_time(kong_http_requests_total{service=~\"$service\", route=~\"$route\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99(ms)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{service=~\"$service\", route=~\"$route\"}[$__interval])) by (le))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "P95(ms)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{service=~\"$service\", route=~\"$route\"}[$__interval])) by (le))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "P90(ms)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{service=~\"$service\", route=~\"$route\"}[$__interval])) by (le))",
     "legendFormat": "P90"
    }
   ]
  }
 ]
}