global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8080']
  - job_name: 'kong'
    scrape_interval: 5s
    static_configs:
    - targets: ['kong:8001']
  - job_name: 'gpu-operator'
    scrape_interval: 5s
    metrics_path: '/gpu-operator/metrics'
    static_configs:
    - targets: ['metrics.k8s.bhasai.samagra.io']
  - job_name: 'dcgm-exporter'
    scrape_interval: 5s
    metrics_path: '/dcgm-exporter/metrics'
    static_configs:
    - targets: ['metrics.k8s.bhasai.samagra.io']
  - job_name: 'kong-gateway-admin'
    scrape_interval: 5s
    metrics_path: '/kong-gateway-admin/metrics'
    static_configs:
    - targets: ['metrics.k8s.bhasai.samagra.io']