services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    restart: always
    command: ["--cache_mode=true", "--default_lua_flags=allow-undeclared-keys"]
    ports:
      - 6380:6379
    volumes:
      - dragonfly:/data

volumes:
  dragonfly: