services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        BARMAN_HOST: ${BARMAN_HOST}
        BARMAN_SSH_PUBLIC_KEY: ${BARMAN_SSH_PUBLIC_KEY}
        POSTGRES_SSH_PUBLIC_KEY: ${POSTGRES_SSH_PUBLIC_KEY}
        POSTGRES_SSH_PRIVATE_KEY: ${POSTGRES_SSH_PRIVATE_KEY}
    restart: always
    command: -c 'config_file=/etc/postgresql/postgresql.conf' -c 'hba_file=/etc/postgresql/pg_hba.conf'
    ports:
      - "5432:5432"
      - "2222:22"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not set}

volumes:
  db: